from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.models.models import Application, ApplicationStatus, Job, NotificationType, User
from app.api.deps import require_recruiter
from app.services.export_service import build_offer_letter_pdf
from app.services.email_service import send_email
from app.services.notification_service import create_notification

router = APIRouter(tags=["offers"])


class OfferLetterRequest(BaseModel):
    salary: str
    joining_date: str
    additional_terms: str | None = None
    mark_as_hired: bool = True


@router.post("/jobs/{job_id}/candidates/{application_id}/offer-letter")
def generate_offer_letter(
    job_id: int, application_id: int, payload: OfferLetterRequest,
    db: Session = Depends(get_db), user: User = Depends(require_recruiter),
):
    application = db.query(Application).filter(Application.id == application_id, Application.job_id == job_id).first()
    if not application:
        raise HTTPException(status_code=404, detail="Application not found")
    job = db.query(Job).filter(Job.id == job_id).first()
    candidate_user = application.candidate.user if application.candidate else None
    if not candidate_user:
        raise HTTPException(status_code=400, detail="Candidate account not found")

    company_name = (
        user.recruiter_profile.company_name if user.recruiter_profile and user.recruiter_profile.company_name else "Our Company"
    )

    pdf_bytes = build_offer_letter_pdf(
        candidate_name=candidate_user.full_name or "Candidate",
        job_title=job.title if job else "the role",
        company_name=company_name,
        salary=payload.salary,
        joining_date=payload.joining_date,
        additional_terms=payload.additional_terms,
        recruiter_name=user.full_name,
    )

    if payload.mark_as_hired:
        application.status = ApplicationStatus.HIRED

    send_email(
        candidate_user.email,
        f"Offer letter - {job.title if job else 'Role'}",
        f"Hi {candidate_user.full_name or 'there'},\n\nCongratulations! Please find your offer letter details for "
        f"{job.title if job else 'the role'} attached/generated by the recruiter. Salary: {payload.salary}. "
        f"Joining date: {payload.joining_date}.\n\nBest,\n{company_name} Hiring Team",
    )
    create_notification(
        db, candidate_user.id, NotificationType.OFFER_GENERATED,
        f"An offer letter has been generated for {job.title if job else 'a role'}",
        link="/candidate/applications",
    )
    db.commit()

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="offer-letter-{application_id}.pdf"'},
    )
