from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response, FileResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.models.models import (
    Application,
    ApplicationStatus,
    Job,
    NotificationType,
    User,
)
from app.api.deps import require_recruiter, require_candidate
from app.services.export_service import build_offer_letter_pdf
from app.services.email_service import send_email
from app.services.notification_service import create_notification


router = APIRouter(tags=["offers"])


class OfferLetterRequest(BaseModel):
    salary: str
    joining_date: str
    additional_terms: str | None = None
    mark_as_hired: bool = True


@router.post("/jobs/{job_id}/candidates/{application_id}/offer-letter")
def generate_offer_letter(
    job_id: int,
    application_id: int,
    payload: OfferLetterRequest,
    db: Session = Depends(get_db),
    user: User = Depends(require_recruiter),
):
    application = (
        db.query(Application)
        .filter(
            Application.id == application_id,
            Application.job_id == job_id,
        )
        .first()
    )

    if not application:
        raise HTTPException(
            status_code=404,
            detail="Application not found",
        )

    job = db.query(Job).filter(Job.id == job_id).first()

    candidate_user = (
        application.candidate.user
        if application.candidate
        else None
    )

    if not candidate_user:
        raise HTTPException(
            status_code=400,
            detail="Candidate account not found",
        )

    company_name = (
        user.recruiter_profile.company_name
        if user.recruiter_profile
        and user.recruiter_profile.company_name
        else "Our Company"
    )

    pdf_bytes = build_offer_letter_pdf(
        candidate_name=candidate_user.full_name or "Candidate",
        job_title=job.title if job else "the role",
        company_name=company_name,
        salary=payload.salary,
        joining_date=payload.joining_date,
        additional_terms=payload.additional_terms,
        recruiter_name=user.full_name,
    )

    # ---------------------------------------------------------
    # Save offer letter so candidate can download it later
    # ---------------------------------------------------------
    offers_dir = Path("uploads") / "offer_letters"
    offers_dir.mkdir(parents=True, exist_ok=True)

    filename = f"offer-letter-{application_id}.pdf"
    file_path = offers_dir / filename

    file_path.write_bytes(pdf_bytes)

    application.offer_letter_path = str(file_path)
    application.offer_letter_filename = filename

    if payload.mark_as_hired:
        application.status = ApplicationStatus.HIRED

    send_email(
        candidate_user.email,
        f"Offer letter - {job.title if job else 'Role'}",
        f"Hi {candidate_user.full_name or 'there'},\n\n"
        f"Congratulations! Please find your offer letter details for "
        f"{job.title if job else 'the role'} attached/generated by the recruiter. "
        f"Salary: {payload.salary}. "
        f"Joining date: {payload.joining_date}.\n\n"
        f"Best,\n{company_name} Hiring Team",
    )

    create_notification(
        db,
        candidate_user.id,
        NotificationType.OFFER_GENERATED,
        f"An offer letter has been generated for "
        f"{job.title if job else 'a role'}",
        link="/candidate/applications",
    )

    db.commit()

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": (
                f'attachment; filename="{filename}"'
            )
        },
    )


# ---------------------------------------------------------
# Candidate: Download own offer letter
# ---------------------------------------------------------
@router.get("/applications/{application_id}/offer-letter")
def download_offer_letter(
    application_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(require_candidate),
):
    application = (
        db.query(Application)
        .filter(Application.id == application_id)
        .first()
    )

    if not application:
        raise HTTPException(
            status_code=404,
            detail="Application not found",
        )

    candidate_user = (
        application.candidate.user
        if application.candidate
        else None
    )

    if not candidate_user:
        raise HTTPException(
            status_code=404,
            detail="Candidate account not found",
        )

    # Candidate can only download their own offer letter
    if candidate_user.id != user.id:
        raise HTTPException(
            status_code=403,
            detail="You are not allowed to access this offer letter",
        )

    if application.status != ApplicationStatus.HIRED:
        raise HTTPException(
            status_code=400,
            detail="Offer letter is available only for hired applications",
        )

    if not application.offer_letter_path:
        raise HTTPException(
            status_code=404,
            detail="Offer letter has not been generated yet",
        )

    file_path = Path(application.offer_letter_path)

    if not file_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Offer letter file not found",
        )

    filename = (
        application.offer_letter_filename
        or f"offer-letter-{application_id}.pdf"
    )

    return FileResponse(
        path=str(file_path),
        media_type="application/pdf",
        filename=filename,
    )